from . import egp_hr_employee
from . import egp_hr_publication
from . import egp_hr_experience
from . import egp_hr_health
from . import egp_hr_travel
from . import egp_hr_property
from . import egp_hr_education
from . import egp_hr_relatives
from . import egp_hr_district
from . import egp_hr_language
from . import egp_hr_exam
from . import egp_hr_training
from . import egp_hr_punishment
from . import egp_hr_reward
from . import egp_hr_appraisal
from . import egp_hr_retirement
from . import egp_hr_guarantee
from . import egp_hr_document_attachment
from . import egp_hr_fire